Repository AnimatiWA/AnimatiWeb, pull requests merged in 2025-08, with the labels that each got.

#92 Corregir error de llamada a servicio Sales
  AnimatiWeb Angular/AnimatiWeb/src/app/pages/admin/sales/sales.component.ts
Labels: bug

#91 Whatsapp button visible.
  AnimatiWeb Angular/AnimatiWeb/src/app/app.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/app.component.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/footer/footer.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/footer/footer.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/promo-modal/promo-modal.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/promo-modal/promo-modal.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/whatsapp-button/whatsapp-button.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/whatsapp-button/whatsapp-button.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/whatsapp-button/whatsapp-button.component.spec.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/whatsapp-button/whatsapp-button.component.ts
  AnimatiWeb Angular/AnimatiWeb/src/assets/img/modal-totoro.png
  AnimatiWeb Angular/AnimatiWeb/src/assets/img/playstore-badge.png
  AnimatiWeb Angular/AnimatiWeb/src/assets/img/whatsapp-icon.png
Labels: enhancement

#93 Correcciones en navbar / Bar informativo.
  AnimatiWeb Angular/AnimatiWeb/src/app/app.component.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/pages/pagina-principal/pagina-principal.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/pages/pagina-principal/pagina-principal.component.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/footer/footer.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/footer/footer.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/info-bar/info-bar.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/info-bar/info-bar.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/info-bar/info-bar.component.spec.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/info-bar/info-bar.component.ts
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/nav/nav.component.css
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/nav/nav.component.html
  AnimatiWeb Angular/AnimatiWeb/src/app/shared/promo-modal/promo-modal.component.html
  AnimatiWeb Angular/AnimatiWeb/src/assets/img/footer-background.png
Labels: bug, enhancement
